### ISSUE TITLE
Mountpoint directory should not be 0777 world writable by default

### ISSUE THREAD

**Issue by lathiat** [echocat/puppet-nfs#15]
manifests/mkdir.pp defaults to creating the mount-point directory with world-writable permissions (0777)

This was introduced in the following commit:
968117be0926164c57eda5653b9bf2f7e1c8f5b3 added gentoo compatibility

It is not desirable to create a mountpoint as world writable by default, as if
the filesystem is not mounted any user can write data that may be inadvertently
used by another service and security context.

Additionally, the directory assumes permissions from the NFS server once mounted
which will then be modified by this resource to make the entire NFS share world
writable on all servers.

This option is configurable and any user requiring this behaviour can override
the default.

**Comment by lathiat** [comment]
Pull request above for my solution.  Open for discussion.

Another possible solution may be to set permissions, owner and group to undef and inherit the puppet defaults.  I thought about it, but I think since this is a mount-point which is in some ways a "special purpose directory", that it is reasonable to provide defaults here over the standard defaults.

**Comment by dwerder** [comment]
Changing the defaults at this point will do nothing, because the permession are already set in `nfs::client::mount` and propageted to `nfs::mkdir`

And in the normal usage you shouldn't call `nfs::mkdir` by yourself.

Another point is, that this wpould change the default behavior of this module. So the question is, which permissions are most likely used.

**Comment by lathiat** [comment]
Good point, I missed that and that would need to be adjusted as well.  I'll update the pull request.

I do not see any valid reason for having the directory set to 0777 as a general case.  There is no functionality granted by this as far as I am aware.  If anyone knows otherwise, please share!


The original commit was for "Gentoo compatibility", so there is no clue here as to why that was made.  I suspect it was inadvertently/innocently added as the 0755 default was hard coded at the time  (not configurable, as it is now) and the contributor likely needed 0777 in their specific environment.

The general use case that I can imagine where you may use it, is that you are mounting a "scratch" directory to be used by multiple users for random files that don't have other pre-configured directories.


While it would change the defaults, and change peoples deployments in production, I feel that the change risk is justified/mitigated by:
- Anyone using librarian-puppet or similar will have it locked to a specific version, and are more likely to review the update than blindly update
- The current case results in both local and network-wide changes to make a directory world writable and thus insecure.  This is highly undesirable and justifies a default-breaking change IMHO.
- In the case the directory is not mounted for some reason (e.g. network error), any user could create files expected to exist that may have had stricter permissions and perhaps trick another user or service into using a malicious payload
- The updated default will be "default secure", configurability exists for users requiring the existing behaviour to easily transition to the new change


An alternative possibility would be to set the mode, user and group to undef by default.   This would have four main effects:
 (1) It would use the system defaults (which are the same, unless the user has changed them globally in the site manifest)
 (2) As they are unspecified, the initial directory creation will set the defaults however it will not enforce a change on the resultant directory once mounted.  I do feel there is some merit to that behaviour.
 (3) Possibly undesirable effect of modifying someones mount-point to be whatever they have set as a default in their manifest, I don't think this is a very common case however.
 (4) Possibly undesirable effect: existing installations will probably not revert from 0777 to 0755.  This is good form a "not breaking things" point of view, but is bad from a "securing things" point of view.
