### ISSUE TITLE
Could not find init script or upstart conf file for 'nfs-common' on Ubuntu 14.04LTS

### ISSUE THREAD

**Issue by NauxLiu** [echocat/puppet-nfs#27]
My manifest:
```
$server = 'nfs.localdomain'

  class { 'nfs::server':
    nfs_v4 => true,
    # nfs_v4_idmap_domain => $::domain,
  }

  Nfs::Client::Mount::Nfs_v4::Root <<| server == $server |>> { 
    mount => "/srv/$server",
  }
```

```
Error: /Stage[main]/Nfs::Client::Debian::Service/Service[idmapd]: Could not evaluate: Could not find init script or upstart conf file for 'nfs-common'
```

**Comment by InfernoZeus** [comment]
I have the same error message. Did you solve this somehow?

**Comment by dwerder** [comment]
The error could be at this line 

https://github.com/echocat/puppet-nfs/blob/master/manifests/client/debian/service.pp#L15

At the moment Debian and Ubuntu share the same config in this module. On Debian distros the nfs daemon name is "nfs-common" and on Ubuntu it seems to be "idmapd".

So I am not the debian/ubuntu guy. Can someone check if I am right?
@InfernoZeus can you try if you get the error, if you just delete the this line?

If it works, then the best solution would be to have a seperate config for Ubuntu and Debian.

**Comment by dwerder** [comment]
@NauxLiu How do you solve the problem?

**Comment by InfernoZeus** [comment]
Thanks @dwerder, I just commented out the suggested line, and it seems to be working fine now.

**Comment by dwerder** [comment]
PR #44 should fix it

**Comment by dwerder** [comment]
@InfernoZeus You can use the develop branch to try the change.
