### ISSUE TITLE
Ability to set owner & group on directory within a server::export resource

### ISSUE THREAD

**Issue by JoshiiSinfield** [echocat/puppet-nfs#30]
Hi,

We have the need to set the owner&group on the folder location for server::export folder, however server::export doesn't have parameters to set owner & group.

I notice that nfs::mkdir has params to support it.

Cheers,
Josh

**Comment by JoshiiSinfield** [comment]
I'll push a patchset up - just wondering if you have any views/preferences on how it should be done or if simply adding parameters to server::export and passing through to nfs::mkdir will suffice?

Josh.

**Comment by dwerder** [comment]
I have no preference. Sounds ok to me. Waiting for the PR.

**Comment by dwerder** [comment]
Please add an example in the README.

**Comment by InfernoZeus** [comment]
Any chance of a release including this patch?

**Comment by dwerder** [comment]
I will create the next puppetforge release next week. Until then u can use the github master

**Comment by InfernoZeus** [comment]
Awesome, thanks! :)

**Comment by dwerder** [comment]
Version 1.6.0 is released: https://forge.puppetlabs.com/echocat/nfs

**Comment by InfernoZeus** [comment]
Awesome, thanks!
