### ISSUE TITLE
Redhat NFS lock service name is incorrect for version 7

### ISSUE THREAD

**Issue by lmvlmv** [echocat/puppet-nfs#48]
Looks like Redhat changed the service name in 7 but not to 'rpc-statd' but to 'nfs-lock'

in nfs/manifests/client/redhat/service.pp this section:

    service {'nfslock':
        ensure    => running,
        name      => $::nfs::client::redhat::params::osmajor ? {
        7       => 'rpc-statd',
        default => 'nfslock'
    },

Should read

    service {'nfslock':
        ensure    => running,
        name      => $::nfs::client::redhat::params::osmajor ? {
        7       => 'nfs-lock',
        default => 'nfslock'
    },

Tested with RHEL7.0 and RHEL7.1

**Comment by dwerder** [comment]
That should not make any difference because the service enabled option is set to undef for rh7
See https://github.com/echocat/puppet-nfs/blob/develop/manifests/client/redhat/service.pp#L15

```puppet
  service {'nfslock':
    ensure    => running,
    name      => $::nfs::client::redhat::params::osmajor ? {
      7       => 'rpc-statd',
      default => 'nfslock'
    },
    enable    => $::nfs::client::redhat::params::osmajor ? {
      7       => undef,
      default => true
    },
    hasstatus => true,
    require   => $::nfs::client::redhat::params::osmajor ? {
      7 => Service['rpcbind'],
      6 => Service['rpcbind'],
      5 => [Package['portmap'], Package['nfs-utils']]
    },
  }
```

**Comment by lmvlmv** [comment]
Shouldn't but it does. "rpc-statd" doesn't exist as a service in RH7, hence the failure.

Looking at a similar module: https://github.com/haraldsk/puppet-module-nfs/blob/master/manifests/client/redhat/service.pp

Looks like redhat were annoyingly inconsistent with their naming...

**Comment by dwerder** [comment]
This is the PR, which initial changed nfs-lockd to rpc-bind:

https://github.com/echocat/puppet-nfs/commit/fabde800cad515ee02d477852a1685f879f60f78#diff-ca1c89bb0c2c8b158086c5edde1aa5b7

So if you can test it, we could revert the service name.

**Comment by roidelapluie** [comment]
@dwerder rpc-statd is fine to me

**Comment by roidelapluie** [comment]
@lmvlmv the module you link is the old version of this module.

**Comment by roidelapluie** [comment]
@dwerder 

```
# systemctl status nfslock
● rpc-statd.service - NFS status monitor for NFSv2/3 locking.
```

nfslock is an alias for rpc-statd. So I would continue to use rpc-statd.
