### ISSUE TITLE
Ubuntu 12.04 Could not find init script or upstart conf file for 'rpcbind'

### ISSUE THREAD

**Issue by amosshapira** [echocat/puppet-nfs#50]
This might be related to issue #27 - a simple `include nfs::servers` on Ubuntu 12.04 results in:

```
Error: /Stage[main]/Nfs::Client::Ubuntu::Service/Service[rpcbind]: Could not evaluate: Could not find init script or upstart conf file for 'rpcbind'
```

adding `provider => 'init'` to the `service` resource in `manifests/client/ubuntu/service.pp` solved this problem. Perhaps this should be set via params where it determines the major os version.

**Comment by dwerder** [comment]
Thanks for the hint. Do you want to send a pull request?

**Comment by amosshapira** [comment]
I'll try to get to it but right now I'm overwhelmed with work so can't commit on time. I suspect that the solution requires some condition on `$::operatingsystemmajrelease` to know which provider to choose.
Thanks for providing this module.
