### ISSUE TITLE
Continued maintainence of puppet-nfs

### ISSUE THREAD

**Issue by haraldsk** [echocat/puppet-nfs#7]
Since there isn't any private way of contacting you I'll just leave this here publicly.

I authored alot of the original code of this module before the fork. I would have liked to continue maintaining it, but I have to realize that i just don't have the time for it right now.

I have a huge backlog of PRs, which is just don't have enough time to merge inn and give the quality assurance it would need. If you feel you'll be able to spend more time on this. I'll be happy to put up a deprecation message on my repo and fon the forge and tell people to submit PRs to your fork instead.

**Comment by dwerder** [comment]
Thanks for the message. I am also only one person, so my first goal (and the reason I forked your module) is a 1.2.0 release for the forge. Just bugfixes and some enhancements like the gentoo/rhel7 support. I do not have the time for a complete rewrite or something like that. But with that new release we could begin with more babysteps in the future.

So I would like to add you to the github commit group of the fork. (Two people with little time are better then none ;-)

My plan is a release on the forge in the next weeks. After this we will see, if it is accepted and maybe then a deprecation message would be fine. I do not want to create the 666 nfs module.

**Comment by haraldsk** [comment]
That sounds like a sensible way to go about it. I don't have any systems with NFS so I don't use this module that actively any more. What is important to me is to try and "save" some of the work that has been contributed by various people, without turning the module into total spaghetti while doing so.

I have some PR that are mostly feature based but are very low hanging fruit.  I can try and port them over and touch them up and save as seperate branches for now. Then we can look into merging them in after you have made a new stable version for the forge. 

I'm not worried about this becoming the #345234 NFS module, because most of the other modules are either quite lacking or they must be integrated into an entire eco system of modules written by the author to work. 

I'll hold off on the deprecation message untill you do a forge release.

**Comment by dwerder** [comment]
I have juste release version 1.2.0 on puppetforge. So we can wait how this performce. If there are no major bug reports in the next weeks you can declare the old module as deprecated.

**Comment by haraldsk** [comment]
That's excellent, congrats with the release.

**Comment by dwerder** [comment]
I think the release is out long enough. You can mark the old repo and forge as deprecated if you want.

**Comment by haraldsk** [comment]
Excellent. I have put a deprecation message on my github project page.

On Mon, Feb 16, 2015 at 2:39 PM, Daniel Werdermann <notifications@github.com
> wrote:

> I think the release is out long enough. You can mark the old repo and
> forge as deprecated if you want.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/echocat/puppet-nfs/issues/7#issuecomment-74509261>.
>



-- 
Harald
