### ISSUE TITLE
Nfs::Server::Debian/File_line[rpc-mount-options] does not depend on Package['nfs-kernel-server']

### ISSUE THREAD

**Issue by rbroemeling** [echocat/puppet-nfs#75]
As authored, File_line[rpc-mount-options] in manifests/server/debian.pp has no dependency on Package['nfs-kernel-server']. This causes it to break, sometimes, when puppet chooses to order things such that the File_line is executed before the package is installed (at this point the file that the stanza is attempting to modify does not exist, and thus things explode).

This can be fixed by adding `require => Package['nfs-kernel-server']` to the rpc-mount-options file_line declaration, so that it looks like this:

```
    file_line { 'rpc-mount-options':
      ensure  => present,
      path    => '/etc/default/nfs-kernel-server',
      line    => "RPCMOUNTDOPTS=\"--manage-gids --port ${mountd_port} --num-threads ${mountd_threads}\"",
      match   => '^#?RPCMOUNTDOPTS',
      require => Package['nfs-kernel-server'];
    }
```

**Comment by dwerder** [comment]
Do you want to send a pull request against develop branch?

**Comment by rbroemeling** [comment]
I sent the requested PR. Note that the Debian version is the only one that I am certain of, but I _expect_ (i.e. guess) that the changes to the Ubuntu and Redhat versions are correct as well.

**Comment by dwerder** [comment]
Looks fine to me and is merged.
