### ISSUE TITLE
Setting nfs::server::mountd_threads parameter has no effect

### ISSUE THREAD

**Issue by cjmachado** [echocat/puppet-nfs#82]
Changing the value of parameter has no effect because the code simply does not use this parameter. To fix this, I added the following code (just for redhat as an example):

# nfs::server::redhat

file_line { 'rpc-mount-args':
    ensure => present,
    path   => '/etc/sysconfig/nfs',
    line   => "RPCMOUNTDOPTS=${mountd_threads}",
    match  => '^#?RPCMOUNTDOPTS='
  } ~> Service[$service_name]

**Comment by dwerder** [comment]
That will not work, because you simply would set RPCMOUNTDOPTS=1 .
I fiexed it in develop branch

**Comment by cjmachado** [comment]
Thank you Daniel.
