### ISSUE TITLE
Ubuntu 16.04: service imapd is not available

### ISSUE THREAD

**Issue by dploeger** [echocat/puppet-nfs#84]
Ubuntu 16.04 runs Systemd and apparently, the service scripts for idmapd are not available (the systemd-modules are linked to /dev/null)

Because of this, running the module yields the following result:

```
Error: Could not start Service[idmapd]: Execution of '/usr/sbin/service idmapd start' returned 1: Failed to start idmapd.service: Unit idmapd.service is masked.
```

I guess, you should simply remove the start of the service for Ubuntu >= 16.04.

**Comment by dwerder** [comment]
Fixed in develop branch.
