### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by rendhalver** [echocat/puppet-nfs#90]
Hi.

We are starting to roll out servers with Ubuntu 16.04 and there seems to be a couple of issues that are fixed but not released.
Do you have a plan for releasing a new version anytime soon with those fixes?

**Comment by dwerder** [comment]
You're right, the forge release for 1.9.0 is missing. I will see for it tomorrow.

**Comment by rendhalver** [comment]
Awesome. Thank you!

**Comment by dwerder** [comment]
Done.
